### ISSUE TITLE
Design Database

### ISSUE THREAD

**Issue by Trong-Nguyen-DT** [dtvn-training/2024_dn_java-1_blog-review-film#4]
- [x] Database analysis of project
- [x] Create tables
- [x] Using Draw.io to design tables & relationship database

**Comment by Trong-Nguyen-DT** [comment]
Link Database Diagram: https://app.diagrams.net/#G1Z0ncNEbms9cagTpdop5wHNInQNoS4kae#%7B%22pageId%22%3A%22LS6wrMC9ZYNtka0xdaUN%22%7D

**Comment by hoa-doan** [comment]
Bổ sung thêm các field common (insert_date, insert_by, update_date, update_by, delete_flag) cho all table nhé
Thêm table category, update thêm các field ngày tháng....

**Comment by Trong-Nguyen-DT** [comment]
Em đã design lại Database, anh review giúp em ạ @hoa-doan https://app.diagrams.net/#G1Z0ncNEbms9cagTpdop5wHNInQNoS4kae#%7B%22pageId%22%3A%22LS6wrMC9ZYNtka0xdaUN%22%7D
