### ISSUE TITLE
Design API

### ISSUE THREAD

**Issue by Trong-Nguyen-DT** [dtvn-training/2024_dn_java-1_blog-review-film#5]
- [x] Function analysis of project
 - [x] Using Swagger to design API

**Comment by Trong-Nguyen-DT** [comment]
Link Swagger to design API: https://app.swaggerhub.com/apis/TRONGNGUYEN2002NGUYE/ReviewFilm/1.0.0#/FilmResponse

**Comment by hoa-doan** [comment]
design response dạng generic API nhé
Ex: 
code: 
message: 
data:

**Comment by Trong-Nguyen-DT** [comment]
Em đã fix xong API, anh review lại giúp em @hoa-doan https://app.swaggerhub.com/apis/TRONGNGUYEN2002NGUYE/ReviewFilm/1.0.0#/FilmResponse
